### ISSUE TITLE
Release 2.5.0 checklist

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli-bundle#187]
- [x] Revert `wp-cli/wp-cli` dependency in `wp-cli/config-command` back to a stable tag [[config-command#106](https://github.com/wp-cli/config-command/issues/106)]
- [x] Revert `wp-cli/wp-cli` dependency in `wp-cli/package-command` back to a stable tag [[package-command#118](https://github.com/wp-cli/package-command/issues/118)]
- [x] Plugin and theme commands break on custom folder structures [[extension-command#247](https://github.com/wp-cli/extension-command/issues/247)]
- [x] Revert `wp-cli/wp-cli` dependency in `wp-cli/search-replace-command` back to a stable tag [[search-replace-command#149](https://github.com/wp-cli/search-replace-command/issues/149)
- [x] Revert `wp-cli/wp-cli` dependency in `wp-cli/db-command` back to a stable tag [[db-command#181](https://github.com/wp-cli/db-command/issues/181)
- [x] Revert `wp-cli/wp-cli` dependency in `wp-cli/entity-command` back to a stable tag [[entity-command#303](https://github.com/wp-cli/entity-command/issues/303)

**Comment by chesio** [comment]
Here are some more commands that I am aware of that currently depend on wp-cli/dev-master:
* https://github.com/wp-cli/db-command/
* https://github.com/wp-cli/entity-command/

**Comment by tristanbes** [comment]
Hello, @schlessera 
Thank you for making `wp-cli` & `wp-cli-bundle` compatible with composer 2.

Composer 2 has been released on _October 24th 2020_. Yet, no stable release of `wp-cli` `wp-cli-bundle` provide this support.

What is missing / Holding back on publishing a stable release ?

Thank you
