### ISSUE TITLE
Issue checklist for v2.1.0

### ISSUE THREAD

**Issue by schlessera** [wp-cli/wp-cli-bundle#36]
Checklist of open issues we want to include for release v2.1.0:

**[`wp-cli/db-command`](https://github.com/wp-cli/db-command)**

- [x] [`--size_format` not working correct for DB size](https://github.com/wp-cli/db-command/issues/107)

**[`wp-cli/entity-command`](https://github.com/wp-cli/entity-command)**

- [ ] ~[`wp post generate --post_content` hangs if there's no STDIN](https://github.com/wp-cli/entity-command/issues/175)~ (does not work within Behat)

**[`wp-cli/extension-command`](https://github.com/wp-cli/extension-command)**

- [x] [`plugin update` does not fail on bad file permissions](https://github.com/wp-cli/extension-command/issues/90)
- [ ] ~[`wp theme mod get --all` produces malformed output for non-tabular formats](https://github.com/wp-cli/extension-command/issues/96)~ (punted)

**[`wp-cli/i18n-command`](https://github.com/wp-cli/i18n-command)**

- [ ] ~[Invalid MD5 hashes in make-json command](https://github.com/wp-cli/i18n-command/issues/120)~ (invalid)

**[`wp-cli/language-command`](https://github.com/wp-cli/language-command)**

- [x] [PHP notice on updating theme translations with no updates](https://github.com/wp-cli/language-command/issues/58)
- [x] [Allow to install language packs for all plugins](https://github.com/wp-cli/language-command/issues/59)

**[`wp-cli/scaffold-command`](https://github.com/wp-cli/scaffold-command)**

- [x] [Block scaffold command produces a syntax error when used with `--theme` argument](https://github.com/wp-cli/scaffold-command/issues/175)

**[`wp-cli/wp-cli`](https://github.com/wp-cli/wp-cli)**

- [x] [`--prompt` should skip flags that have been included in the command](https://github.com/wp-cli/wp-cli/issues/4762) _(to be discussed)_
- [x] [WP-CLI does not use the same way as wordpress to locate the `wp-config.php`](https://github.com/wp-cli/wp-cli/issues/4856)
- [x] [Packages cannot override bundled commands in Phar anymore](https://github.com/wp-cli/wp-cli/issues/4987)
- [x] [WP CLI can no longer be installed on Windows](https://github.com/wp-cli/wp-cli/issues/5018)
- [x] [Bump PHP version check in bootstrap code to v5.4+](https://github.com/wp-cli/wp-cli/issues/5037)

---

Fixes #41
